<?php

namespace Punnet\SiteBundle\Entity\Abonnement;

use Doctrine\ORM\EntityRepository;

/**
 * RegionAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionAbonnementRepository extends EntityRepository
{
}
