<?php

namespace Punnet\SiteBundle\Entity\Abonnement;

use Doctrine\ORM\EntityRepository;

/**
 * UserAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAbonnementRepository extends EntityRepository
{
	public function countFollowers($user) // Compte le nombre de personne qui follow l'utilisateur.
	{
		return $this->createQueryBuilder('u')
					->select('count(u.id)')
					->where('u.user = :user')
					->setParameter('user' , $user)
					->getQuery()
					->getSingleScalarResult();
	}
}
