<?php

namespace Punnet\SiteBundle\Entity\Abonnement;

use Doctrine\ORM\EntityRepository;

/**
 * UserAbonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAbonnementRepository extends EntityRepository
{
}
