<?php

namespace Punnet\SiteBundle\Entity\ParentCategorie\ParentCategorie;

use Doctrine\ORM\EntityRepository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentCategorieRepository extends EntityRepository
{
}
