punnet_homepage:
    pattern:  /
    defaults: { _controller: PunnetSiteBundle:Site:accueil }
    
punnet_comingsoon:
    pattern:  /coming-soon
    defaults: { _controller: PunnetSiteBundle:Site:comingSoon }

punnet_showAnnonce:
    pattern:  /show-annonce/{annonce}
    defaults: { _controller: PunnetSiteBundle:Site:showAnnonce }

punnet_showRegion:
    pattern:  /show-region/{region}/{ordre}
    defaults: { _controller: PunnetSiteBundle:Site:showRegion, region:toutes-les-regions ,ordre: asc }

punnet_showUser:
    pattern:  /show-user
    defaults: { _controller: PunnetSiteBundle:Site:showUser }

punnet_showAllUserAnnonce:
    pattern:  /show-user-annonce/user/{user}
    defaults: { _controller: PunnetSiteBundle:site:showAllUserAnnonce }

punnet_showUserBord:
    pattern:  /bord
    defaults: { _controller: PunnetSiteBundle:Bord:showUserBord }

punnet_depot:
    pattern:  /bord/depot
    defaults: { _controller: PunnetSiteBundle:Bord:depotAnnonce }

punnet_showUserAnnonce:
    pattern:  /bord/show-annonce
    defaults: { _controller: PunnetSiteBundle:Bord:showUserAnnonce }

punnet_editAnnonce:
    pattern:  /bord/edit-annonce/{id}
    defaults: { _controller: PunnetSiteBundle:Bord:editUserAnnonce }
    requirements:
        id: \d+
